// collectors/config/himalayasCompanies.js
//
// Optional allowlist for himalayas.js. Names captured live from
// https://himalayas.app/jobs/api (the `companyName` field, verbatim).
//
// EMPTY ARRAY = no filtering (default) — the collector keeps every job on
// the feed, same as before this list existed. Populate it to restrict to
// specific companies only.

const companies = [
  "A-LIGN",
  "AbbVie",
  "Affirm",
  "Akamai Technologies",
  "American Institutes for Research",
  "Arrow Electronics, Inc.",
  "Associated Press",
  "Banner Health",
  "BeiGene",
  "Bristol Myers Squibb",
  "Capgemini Technology Services",
  "Capita",
  "Circle",
  "Concentrix",
  "Crowdstrike",
  "Cyera",
  "Dataminr",
  "Ecolab Inc.",
  "EverCommerce",
  "Fullscript",
  "Gartner",
  "General Dynamics Mission Systems",
  "Genesys",
  "Guesty",
  "Henry Schein",
  "HireVue Inc",
  "Human Interest",
  "Jensen Hughes",
  "Jonas Software",
  "Lehigh Valley Health Network",
  "Leidos",
  "LifeStance Health",
  "MariaDB",
  "Merck",
  "Model N",
  "Motorola Solutions",
  "NVIDIA",
  "National University",
  "Oscar",
  "Parallels",
  "Peraton",
  "Philips",
  "Premier Inc.",
  "Progressive Leasing",
  "Protective",
  "PTC",
  "Quicken Loans",
  "RELX",
  "Remote",
  "RxSense",
  "SGS",
  "Sedgwick",
  "ServiceNow",
  "ServiceTitan",
  "Spring Health",
  "Sutter Health",
  "The Cigna Group",
  "The Ohio State University",
  "The RealReal",
  "Torc Robotics",
  "Trend Micro",
  "Unisys",
  "Veeam Software",
  "Western Governors University",
  "Wipfli",
  "Zeta Global",
];

export default companies;
