// backend/src/services/resume/improvedResumeDoc.service.js
//
// Renders the "Improve Resume" JSON (already generated by Claude) into a
// formatted .docx. Pure formatting — no AI call, no extra cost.

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";

const BRAND = "5A2FE6";
const SLATE = "334155";

function heading(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 320, after: 120 },
    children: [new TextRun({ text, bold: true, color: BRAND })],
  });
}

function body(text, opts = {}) {
  return new Paragraph({
    spacing: { after: 70 },
    ...(opts.bullet ? { bullet: { level: 0 } } : {}),
    children: [new TextRun({ text, color: SLATE, size: 22 })], // 11pt
  });
}

/**
 * Renders a full rewritten resume (REWRITE_SCHEMA shape) as a clean,
 * single-column, ATS-safe Word document: standard section headers, no tables,
 * no text boxes, standard font.
 * @returns {Promise<Buffer>} .docx file contents
 */
export async function buildFullResumeDocx(resume = {}) {
  const {
    name = "", title = "", contact = {}, summary = "",
    key_achievements = [], skill_groups = [], experience = [],
    education = [], certifications = [], projects = [],
  } = resume;

  const contactBits = [
    contact.email, contact.phone, contact.location,
    ...(contact.links || []),
  ].filter(Boolean);

  // Compact spacing throughout — the layout targets a two-page document.
  const section = (text) =>
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 180, after: 70 },
      border: { bottom: { style: "single", size: 6, color: "CBD5E1" } },
      children: [new TextRun({ text: text.toUpperCase(), bold: true, color: SLATE, size: 23 })],
    });

  const children = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 30 },
      children: [new TextRun({ text: name || "Resume", bold: true, size: 38, color: SLATE })],
    }),
  ];

  if (title) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 40 },
        children: [new TextRun({ text: title, color: BRAND, size: 24, bold: true })],
      }),
    );
  }

  if (contactBits.length) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 160 },
        children: [new TextRun({ text: contactBits.join("  |  "), color: "64748B", size: 20 })],
      }),
    );
  }

  if (summary) {
    children.push(section("Professional Summary"));
    children.push(body(summary));
  }

  if (key_achievements.length) {
    children.push(section("Key Achievements"));
    for (const a of key_achievements) children.push(body(String(a), { bullet: true }));
  }

  if (skill_groups.length) {
    children.push(section("Skills"));
    for (const g of skill_groups) {
      const label = g.name && g.name.toLowerCase() !== "skills" ? `${g.name}: ` : "";
      children.push(
        new Paragraph({
          spacing: { after: 60 },
          children: [
            ...(label ? [new TextRun({ text: label, bold: true, color: SLATE, size: 22 })] : []),
            new TextRun({ text: (g.skills || []).join(", "), color: SLATE, size: 22 }),
          ],
        }),
      );
    }
  }

  if (experience.length) {
    children.push(section("Experience"));
    for (const job of experience) {
      children.push(
        new Paragraph({
          spacing: { before: 90, after: 20 },
          children: [
            new TextRun({ text: job.title || "", bold: true, color: SLATE, size: 23 }),
            new TextRun({
              text: job.company ? `  —  ${job.company}` : "",
              color: SLATE,
              size: 23,
            }),
          ],
        }),
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({
              text: [job.location, job.dates].filter(Boolean).join("  ·  "),
              italics: true,
              color: "64748B",
              size: 20,
            }),
          ],
        }),
      );
      for (const b of job.bullets || []) children.push(body(String(b), { bullet: true }));
    }
  }

  if (education.length) {
    children.push(section("Education"));
    for (const ed of education) {
      children.push(
        new Paragraph({
          spacing: { before: 80, after: 20 },
          children: [
            new TextRun({ text: ed.degree || "", bold: true, color: SLATE, size: 22 }),
            new TextRun({
              text: ed.institution ? `  —  ${ed.institution}` : "",
              color: SLATE,
              size: 22,
            }),
            new TextRun({
              text: ed.dates ? `  (${ed.dates})` : "",
              italics: true,
              color: "64748B",
              size: 20,
            }),
          ],
        }),
      );
      if (ed.details) children.push(body(ed.details));
    }
  }

  if (certifications.length) {
    children.push(section("Certifications"));
    for (const c of certifications) children.push(body(String(c), { bullet: true }));
  }

  if (projects.length) {
    children.push(section("Projects"));
    for (const p of projects) {
      children.push(
        new Paragraph({
          spacing: { before: 80, after: 20 },
          children: [new TextRun({ text: p.name || "", bold: true, color: SLATE, size: 22 })],
        }),
      );
      if (p.description) children.push(body(p.description));
    }
  }

  const doc = new Document({
    styles: { default: { document: { run: { font: "Calibri" } } } },
    sections: [
      {
        // 0.6" margins — part of the two-page fit.
        properties: {
          page: { margin: { top: 864, bottom: 864, left: 864, right: 864 } },
        },
        children,
      },
    ],
  });

  return Packer.toBuffer(doc);
}

/**
 * @param {object} improvement  { improved_summary, rewritten_bullets[],
 *   keywords_to_add[], recruiter_feedback[], ats_improvements[] }
 * @param {string} candidateName  used in the title
 * @returns {Promise<Buffer>} .docx file contents
 */
export async function buildImprovedResumeDocx(improvement = {}, candidateName = "") {
  const {
    improved_summary = "",
    rewritten_bullets = [],
    keywords_to_add = [],
    recruiter_feedback = [],
    ats_improvements = [],
  } = improvement;

  const children = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 60 },
      children: [
        new TextRun({
          text: candidateName ? `${candidateName} — Improved Resume` : "Improved Resume",
          bold: true,
          color: SLATE,
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [
        new TextRun({
          text: `AI-optimized suggestions · Generated by AIFAGen · ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
          italics: true,
          color: "94A3B8",
          size: 18,
        }),
      ],
    }),
  ];

  if (improved_summary) {
    children.push(heading("Professional Summary"));
    children.push(body(improved_summary));
  }

  if (rewritten_bullets.length) {
    children.push(heading("Experience — Rewritten Bullets"));
    for (const b of rewritten_bullets) children.push(body(String(b), { bullet: true }));
  }

  if (keywords_to_add.length) {
    children.push(heading("ATS Keywords To Add"));
    children.push(body(keywords_to_add.join("  ·  ")));
  }

  if (recruiter_feedback.length) {
    children.push(heading("Recruiter Feedback"));
    for (const f of recruiter_feedback) children.push(body(String(f), { bullet: true }));
  }

  if (ats_improvements.length) {
    children.push(heading("ATS Improvements"));
    for (const a of ats_improvements) children.push(body(String(a), { bullet: true }));
  }

  const doc = new Document({
    styles: {
      default: { document: { run: { font: "Calibri" } } },
    },
    sections: [{ children }],
  });

  return Packer.toBuffer(doc);
}
