-- AIFAGen base schema. Safe to apply to a fresh project or an existing one.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  company text not null,
  location text,
  description text,
  source text not null,
  source_job_id text not null,
  apply_url text,
  salary text,
  employment_type text,
  skills text[] not null default '{}',
  posted_date timestamptz,
  is_active boolean not null default true,
  last_seen timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint jobs_source_source_job_id_key unique (source, source_job_id)
);

create table if not exists public.resumes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  file_name text not null,
  file_path text not null,
  extracted_text text,
  extracted_skills text[] not null default '{}',
  ai_analysis jsonb,
  uploaded_at timestamptz not null default now()
);

-- Field names match backend/src/services/users/preferences.service.js, which
-- is the only code that commits to a shape (the frontend service does select *).
create table if not exists public.user_job_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  target_role text,
  preferred_location text,
  remote_only boolean not null default false,
  visa_sponsorship boolean not null default false,
  experience_level text,
  min_salary numeric,
  target_companies text[] not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  used_at timestamptz not null default now()
);

create index if not exists resumes_user_uploaded_idx
  on public.resumes (user_id, uploaded_at desc);
create index if not exists jobs_active_expires_idx
  on public.jobs (is_active, expires_at);
create index if not exists ai_usage_user_used_idx
  on public.ai_usage (user_id, used_at desc);

-- Atomically check and consume one AI use. Advisory locking prevents a burst
-- of parallel judge requests from racing past the free-tier daily limit.
create or replace function public.consume_ai_usage(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_plan text;
  current_status text;
  uses_today integer;
begin
  perform pg_advisory_xact_lock(hashtext(p_user_id::text));

  select plan, subscription_status
    into current_plan, current_status
    from public.profiles
   where id = p_user_id;

  if current_plan in ('professional', 'career_accelerator')
     and current_status in ('active', 'trialing') then
    insert into public.ai_usage (user_id) values (p_user_id);
    return true;
  end if;

  if current_plan <> 'free' or current_status <> 'active' then
    return false;
  end if;

  select count(*) into uses_today
    from public.ai_usage
   where user_id = p_user_id
     and used_at >= date_trunc('day', now());

  if uses_today >= 5 then
    return false;
  end if;

  insert into public.ai_usage (user_id) values (p_user_id);
  return true;
end;
$$;

revoke all on function public.consume_ai_usage(uuid) from public;
grant execute on function public.consume_ai_usage(uuid) to service_role;

alter table public.profiles enable row level security;
alter table public.jobs enable row level security;
alter table public.resumes enable row level security;
alter table public.user_job_preferences enable row level security;
alter table public.ai_usage enable row level security;

drop policy if exists "active_jobs_read" on public.jobs;
create policy "active_jobs_read" on public.jobs for select
  to anon, authenticated
  using (is_active and (expires_at is null or expires_at > now()));

drop policy if exists "resumes_select_own" on public.resumes;
create policy "resumes_select_own" on public.resumes for select
  to authenticated using (auth.uid() = user_id);
drop policy if exists "resumes_insert_own" on public.resumes;
create policy "resumes_insert_own" on public.resumes for insert
  to authenticated with check (auth.uid() = user_id);
drop policy if exists "resumes_update_own" on public.resumes;
create policy "resumes_update_own" on public.resumes for update
  to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "resumes_delete_own" on public.resumes;
create policy "resumes_delete_own" on public.resumes for delete
  to authenticated using (auth.uid() = user_id);

drop policy if exists "preferences_own" on public.user_job_preferences;
create policy "preferences_own" on public.user_job_preferences for all
  to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public)
values ('resumes', 'resumes', false)
on conflict (id) do update set public = false;

drop policy if exists "resume_objects_select_own" on storage.objects;
create policy "resume_objects_select_own" on storage.objects for select
  to authenticated
  using (bucket_id = 'resumes' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "resume_objects_insert_own" on storage.objects;
create policy "resume_objects_insert_own" on storage.objects for insert
  to authenticated
  with check (bucket_id = 'resumes' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "resume_objects_update_own" on storage.objects;
create policy "resume_objects_update_own" on storage.objects for update
  to authenticated
  using (bucket_id = 'resumes' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'resumes' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "resume_objects_delete_own" on storage.objects;
create policy "resume_objects_delete_own" on storage.objects for delete
  to authenticated
  using (bucket_id = 'resumes' and (storage.foldername(name))[1] = auth.uid()::text);
