-- supabase/migrations/0016_admin_audit_and_ai_usage.sql
--
-- Two additive changes for the admin portal:
--
-- 1. admin_audit_log — PATCH /api/admin/users/:id/plan grants paid access with
--    no record of who did it. Every privileged admin mutation now writes a row
--    here so plan grants, refunds and job moderation are attributable.
--
-- 2. ai_usage columns — the table only recorded (user_id, used_at), so
--    "which provider served this, what did it cost, which feature called it"
--    was unanswerable. All new columns are nullable: existing rows stay valid
--    and older code that inserts only user_id keeps working.

-- ---------------------------------------------------------------------------
-- 1. Admin audit log
-- ---------------------------------------------------------------------------
create table if not exists public.admin_audit_log (
  id          bigint generated by default as identity primary key,
  actor_id    uuid references auth.users (id) on delete set null,
  actor_email text,
  action      text not null,          -- e.g. 'user.plan_override', 'payment.refund'
  target_type text,                   -- 'user' | 'job' | 'payment' | 'admin'
  target_id   text,
  detail      jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

create index if not exists admin_audit_log_created_idx
  on public.admin_audit_log (created_at desc);
create index if not exists admin_audit_log_actor_idx
  on public.admin_audit_log (actor_id, created_at desc);
create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log (target_type, target_id);

alter table public.admin_audit_log enable row level security;

-- Admins may read the log; nobody may write through the client. The backend
-- writes with the service-role key, which bypasses RLS entirely — an audit
-- trail a client could insert into (or edit) would be worthless.
drop policy if exists "admin_audit_log_read" on public.admin_audit_log;
create policy "admin_audit_log_read"
  on public.admin_audit_log for select
  to authenticated
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- 2. ai_usage attribution
-- ---------------------------------------------------------------------------
alter table public.ai_usage
  add column if not exists provider      text,   -- 'anthropic' | 'groq' | 'gemini'
  add column if not exists model         text,
  add column if not exists feature       text,   -- 'resume_analyze' | 'match' | …
  add column if not exists input_tokens  integer,
  add column if not exists output_tokens integer,
  add column if not exists cost_usd      numeric(10, 6),
  add column if not exists success       boolean not null default true,
  add column if not exists error         text;

create index if not exists ai_usage_provider_idx on public.ai_usage (provider, used_at desc);
create index if not exists ai_usage_feature_idx  on public.ai_usage (feature, used_at desc);
