export default [
  "Remote",
  "United States",

  "California",
  "Texas",
  "New York",
  "Washington",
  "Florida",
  "Virginia",
  "Colorado",
  "Illinois",
  "Massachusetts",
  "Georgia",
  "North Carolina",
  "Pennsylvania",
  "Arizona",
  "Ohio",
  "Michigan",
  "New Jersey",
  "Oregon",
  "Utah",
  "Maryland",
  "Minnesota",

  "San Francisco, CA",
  "San Jose, CA",
  "Los Angeles, CA",
  "San Diego, CA",
  "Seattle, WA",
  "Bellevue, WA",
  "Redmond, WA",
  "New York, NY",
  "Austin, TX",
  "Dallas, TX",
  "Houston, TX",
  "Chicago, IL",
  "Boston, MA",
  "Atlanta, GA",
  "Denver, CO",
  "Phoenix, AZ",
  "Miami, FL",
  "Orlando, FL",
  "Raleigh, NC",
  "Charlotte, NC",
  "Portland, OR",
  "Salt Lake City, UT",
  "Arlington, VA",
  "Washington, DC",
];
